In [ ]:
# from google.cloud import bigquery

# client = bigquery.Client()

# query = """
# SELECT
#   block_number,
#   block_timestamp,
#   ARRAY(
#     SELECT AS STRUCT addr AS address, out.type AS script_type
#     FROM UNNEST(outputs) AS out, UNNEST(out.addresses) AS addr
#     WHERE out.type != 'nonstandard'
#   ) AS real_outputs
# FROM `bigquery-public-data.crypto_bitcoin.transactions`
# WHERE is_coinbase = true
#   AND block_number BETWEEN 0 AND 810908
#   AND block_timestamp_month BETWEEN '2009-01-01' AND '2023-10-01'
# """

# df = client.query(query).to_dataframe()
# df.to_csv("../data/coinbase_addresses_full.csv", index=False)
# print(f"Pulled {len(df)} rows")

In [1]:
from google.cloud import bigquery

client = bigquery.Client()
print(client.project)

poai-research

In [ ]:
# result = client.query("SELECT 1 AS test").to_dataframe()
# print(result)

   test
0     1

In [ ]:
# job_config = bigquery.QueryJobConfig(dry_run=True, use_query_cache=False)

# query = """
# SELECT
#   block_number,
#   block_timestamp,
#   ARRAY(
#     SELECT AS STRUCT addr AS address, out.type AS script_type
#     FROM UNNEST(outputs) AS out, UNNEST(out.addresses) AS addr
#     WHERE out.type != 'nonstandard'
#   ) AS real_outputs
# FROM `bigquery-public-data.crypto_bitcoin.transactions`
# WHERE is_coinbase = true
#   AND block_number BETWEEN 0 AND 810908
#   AND block_timestamp_month BETWEEN '2009-01-01' AND '2023-10-01'
# """

# dry_run_job = client.query(query, job_config=job_config)
# print(f"This query will process {dry_run_job.total_bytes_processed / 1e9:.2f} GB")

This query will process 156.60 GB

In [ ]:
# query = """
# SELECT
#   block_number,
#   block_timestamp,
#   ARRAY(
#     SELECT AS STRUCT addr AS address, out.type AS script_type
#     FROM UNNEST(outputs) AS out, UNNEST(out.addresses) AS addr
#     WHERE out.type != 'nonstandard'
#   ) AS real_outputs
# FROM `bigquery-public-data.crypto_bitcoin.transactions`
# WHERE is_coinbase = true
#   AND block_number BETWEEN 0 AND 810908
#   AND block_timestamp_month BETWEEN '2009-01-01' AND '2023-10-01'
# """

# df = client.query(query).to_dataframe()
# df.to_csv("../data/coinbase_addresses_full.csv", index=False)
# print(f"Pulled {len(df)} rows")

Pulled 810909 rows

In [8]:
df

,block_number,block_timestamp,real_outputs
0,432562,2016-10-02 19:15:59+00:00,[{'address': '1DrK44np3gMKuvcGeFVv9Jk67zodP52e...
1,434680,2016-10-17 09:01:02+00:00,[{'address': '1DrK44np3gMKuvcGeFVv9Jk67zodP52e...
2,433113,2016-10-06 08:35:43+00:00,[{'address': '1JVMpaWzLB1pnkwoQNqK4Z4EimQj5bCK...
3,434383,2016-10-15 03:45:50+00:00,[{'address': '1EFg9XXX1U99pNJJTeQwuuEpbHFW4XS8...
4,435268,2016-10-21 15:27:20+00:00,[{'address': '1EFg9XXX1U99pNJJTeQwuuEpbHFW4XS8...
...,...,...,...
810904,438428,2016-11-11 17:50:12+00:00,[{'address': '1BQLNJtMDKmMZ4PyqVFfRuBNvoGhjigB...
810905,440696,2016-11-26 17:15:59+00:00,[{'address': '1DrK44np3gMKuvcGeFVv9Jk67zodP52e...
810906,439402,2016-11-17 17:51:09+00:00,[{'address': '18cBEMRxXHqzWWCxZNtU91F5sbUNKhL5...
810907,439453,2016-11-18 02:46:12+00:00,[{'address': '18cBEMRxXHqzWWCxZNtU91F5sbUNKhL5...
810908,437275,2016-11-04 03:09:21+00:00,[{'address': '1KFHE7w8BhaENAswwryaoccDb6qcT6Db...

In [9]:
print(df.shape)          # should be (810909, 3)
print(df.dtypes)
df.head(5)

(810909, 3)
block_number                     Int64
block_timestamp    datetime64[us, UTC]
real_outputs                    object
dtype: object

,block_number,block_timestamp,real_outputs
0,432562,2016-10-02 19:15:59+00:00,[{'address': '1DrK44np3gMKuvcGeFVv9Jk67zodP52e...
1,434680,2016-10-17 09:01:02+00:00,[{'address': '1DrK44np3gMKuvcGeFVv9Jk67zodP52e...
2,433113,2016-10-06 08:35:43+00:00,[{'address': '1JVMpaWzLB1pnkwoQNqK4Z4EimQj5bCK...
3,434383,2016-10-15 03:45:50+00:00,[{'address': '1EFg9XXX1U99pNJJTeQwuuEpbHFW4XS8...
4,435268,2016-10-21 15:27:20+00:00,[{'address': '1EFg9XXX1U99pNJJTeQwuuEpbHFW4XS8...

In [10]:
print(df.iloc[0]["real_outputs"])
print(df.iloc[-1]["real_outputs"])

[{'address': '1DrK44np3gMKuvcGeFVv9Jk67zodP52eMu', 'script_type': 'pubkeyhash'}]
[{'address': '1KFHE7w8BhaENAswwryaoccDb6qcT6DbYY', 'script_type': 'pubkeyhash'}]

In [11]:
df["n_addresses"] = df["real_outputs"].apply(len)
df["n_addresses"].value_counts()

n_addresses
1      776074
2       19435
21       1046
5         635
3         334
        ...
257         1
254         1
255         1
300         1
278         1
Name: count, Length: 511, dtype: int64

In [14]:
df_sorted_asc = df.sort_values("block_number", ascending=True)
df_sorted_asc.head(10)

,block_number,block_timestamp,real_outputs,n_addresses
61177,0,2009-01-03 18:15:05+00:00,[{'address': '1A1zP1eP5QGefi2DMPTfTL5SLmv7Divf...,1
58828,1,2009-01-09 02:54:25+00:00,[{'address': '12c6DSiU4Rq3P4ZxziKxzrL5LmMBrzjr...,1
58908,2,2009-01-09 02:55:44+00:00,[{'address': '1HLoD9E4SDFFPDiYfNYnkBLQ85Y51J3Z...,1
58657,3,2009-01-09 03:02:53+00:00,[{'address': '1FvzCLoTPGANNjWoUo6jUGuAG3wg1w4Y...,1
58727,4,2009-01-09 03:16:28+00:00,[{'address': '15ubicBBWFnvoZLT7GiU2qxjRaKJPdkD...,1
59191,5,2009-01-09 03:23:48+00:00,[{'address': '1JfbZRwdDHKZmuiZgYArJZhcuuzuw2Hu...,1
59213,6,2009-01-09 03:29:49+00:00,[{'address': '1GkQmKAmHtNfnD3LHhTkewJxKHVSta4m...,1
58814,7,2009-01-09 03:39:29+00:00,[{'address': '16LoW7y83wtawMg5XmT4M3Q7EdjjUmen...,1
58792,8,2009-01-09 03:45:43+00:00,[{'address': '1J6PYEzr4CUoGbnXrELyHszoTSz3wCsC...,1
59165,9,2009-01-09 03:54:39+00:00,[{'address': '12cbQLTFMXRnSzktFkuoG3eHoMeFtpTu...,1

In [16]:
df_sorted_desc = df.sort_values("block_number", ascending=False)
df_sorted_desc.head(10)

,block_number,block_timestamp,real_outputs,n_addresses
431417,810908,2023-10-06 13:37:21+00:00,[{'address': 'bc1qxhmdufsvnuaaaer4ynz88fspdsxq...,1
430677,810907,2023-10-06 13:37:00+00:00,[{'address': '38XnPvu9PmonFU9WouPXUjYbW91wa5Me...,1
432328,810906,2023-10-06 12:50:15+00:00,[{'address': '1K6KoYC69NnafWJ7YgtrpwJxBLiijWqw...,2
430685,810905,2023-10-06 12:45:49+00:00,[{'address': 'bc1qxhmdufsvnuaaaer4ynz88fspdsxq...,1
432164,810904,2023-10-06 12:36:45+00:00,[{'address': 'bc1qxhmdufsvnuaaaer4ynz88fspdsxq...,1
431718,810903,2023-10-06 12:27:41+00:00,[{'address': '18cBEMRxXHqzWWCxZNtU91F5sbUNKhL5...,1
431717,810902,2023-10-06 12:15:02+00:00,[{'address': '38XnPvu9PmonFU9WouPXUjYbW91wa5Me...,1
432165,810901,2023-10-06 12:01:05+00:00,[{'address': 'bc1qxhmdufsvnuaaaer4ynz88fspdsxq...,1
429813,810900,2023-10-06 11:54:39+00:00,[{'address': 'bc1qnxqs46jyvdf2elelsg96g8xezttc...,2
430075,810899,2023-10-06 11:54:09+00:00,[{'address': '3L8Ck6bm3sve1vJGKo6Ht2k167YKSKi8...,1

In [17]:
print(df[df["block_number"] == 0]["real_outputs"].values)

[array([{'address': '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa', 'script_type': 'pubkey'}],
       dtype=object)                                                                ]

In [18]:
df["n_addresses"].value_counts()

n_addresses
1      776074
2       19435
21       1046
5         635
3         334
        ...
257         1
254         1
255         1
300         1
278         1
Name: count, Length: 511, dtype: int64

In [19]:
multi = df[df["n_addresses"] >= 20].iloc[0]
print(multi["block_number"], multi["block_timestamp"])
for out in multi["real_outputs"][:10]:
    print(out)

434378 2016-10-15 02:46:24+00:00
{'address': '1rHccayux9BGC3gjZHzRegzWSFCEKKUBQ', 'script_type': 'pubkeyhash'}
{'address': '1NH2jqhxMjDkU8rVT14Sxvb8fojiyQMey1', 'script_type': 'pubkeyhash'}
{'address': '19uvYcEzVyXwANnd47H53B15pSwmxx38LM', 'script_type': 'pubkeyhash'}
{'address': '17Y41RekVYUZNz3izL2jvxkvJNuFhaLpCj', 'script_type': 'pubkeyhash'}
{'address': '1FXXxtdJd5PhHPvgfM2zuxkjihEJhamaw8', 'script_type': 'pubkeyhash'}
{'address': '16wZGhYKYW7jtLfvMC6HermF1RPSgnrDux', 'script_type': 'pubkeyhash'}
{'address': '17DA3VHGYD1GyFCZM3KRa53juywRF2XtCD', 'script_type': 'pubkeyhash'}
{'address': '18Jm44GyWxQrcyFVp46xQa6fFg7yKki8bg', 'script_type': 'pubkeyhash'}
{'address': '1PGTh8EWT7jRdCaowp2JX3yVwj84BU1hdH', 'script_type': 'pubkeyhash'}
{'address': '17543UZ6uoQSaScPMTHfg6MoRTrhtjE8mQ', 'script_type': 'pubkeyhash'}